import assert from 'node:assert/strict';
import { mkdtemp,mkdir,writeFile,readFile } from 'node:fs/promises';
import { join } from 'node:path';import { tmpdir } from 'node:os';
import { characterSheet,validateCharacterSet } from '../dist/tools/characterSheetTools.js';
import { runProjectOperation } from '../dist/utils/security.js';
import { makeCanvas,fillRect,encodePng,decodePng } from '../dist/utils/tiles.js';
const root=await mkdtemp(join(tmpdir(),'mcp-character-'));await mkdir(join(root,'Data'));
const image=makeCanvas(64,96);for(let i=0;i<16;i++)fillRect(image,i%4*16+4,Math.floor(i/4)*24+8,8,16,[i+1,20,30,255]);
await writeFile(join(root,'hero.png'),encodePng(image));
const spec={sourcePath:'hero.png',layout:{engine:'xp',columns:4,rows:4},directions:['down','left','right','up'],role:'walking',anchors:Array.from({length:16},()=>({x:8,y:24})),conversion:{engine:'xp',columns:4,rows:4,frameWidth:32,frameHeight:48,scale:2,frames:Array.from({length:16},(_,i)=>({sourceFrame:15-i,anchor:{x:16,y:48}}))}};
const save=()=>writeFile(join(root,'character.json'),JSON.stringify(spec));const call=(a={})=>runProjectOperation(root,undefined,a.dryRun===false,()=>characterSheet(root,{specPath:'character.json',...a}));
await save();let plan=await call();assert.equal(plan.frames.length,16);assert.deepEqual(plan.frames[0].bbox,{x:4,y:8,width:8,height:16});assert.deepEqual(plan.frames[0].bottomCenterOffset,{x:0,y:0});assert.equal(plan.frames[0].transparent,256);
await assert.rejects(call({dryRun:false,outputName:'bad'}),/review evidence/);
spec.review={binding:plan.reviewBinding,evidence:'Explicit synthetic frame mapping and bottom-center anchors reviewed'};await save();const result=await call({dryRun:false,outputName:'converted'});const converted=await decodePng(result.files['character.png']);assert.equal(converted.width,128);assert.equal(converted.height,192);assert.deepEqual([...converted.data.slice((16*128+8)*4,(16*128+8)*4+4)],[16,20,30,255]);
spec.conversion.frames[0].sourceFrame=0;await save();await assert.rejects(call({dryRun:false,outputName:'stale'}),/review evidence/);spec.conversion.frames[0].sourceFrame=15;
spec.conversion.frames[0].anchor.x=0;await save();await assert.rejects(call(),/clips target/);spec.conversion.frames[0].anchor.x=16;
spec.layout.columns=3;await save();await assert.rejects(call(),/divide|4 columns/);spec.layout.columns=4;
spec.layout.engine='mv';await save();await assert.rejects(call(),/never inferred/);spec.layout.engine='xp';
await save();const walkBytes=await readFile(join(root,'character.json'));spec.role='running';await writeFile(join(root,'run.json'),JSON.stringify(spec));await writeFile(join(root,'character.json'),walkBytes);
const set=await runProjectOperation(root,undefined,false,()=>validateCharacterSet(root,{specPaths:['character.json','run.json']}));assert.equal(set.compatibleGeometry,true);assert.equal(set.sheets[1].role,'running');
await assert.rejects(runProjectOperation(root,undefined,false,()=>validateCharacterSet(root,{specPaths:['character.json','character.json']})),/unique/);
console.log('PASS explicit XP layouts, alpha/bbox/anchors, reversed frame mapping, exact 2x conversion, stale-review rejection, clipping/MV refusal and labeled animation-set comparison');
const opaque=makeCanvas(64,96);fillRect(opaque,0,0,64,96,[40,50,60,255]);await writeFile(join(root,'hero.png'),encodePng(opaque));
const inspected=await call();assert.equal(inspected.warnings.filter(x=>x.includes('opaque background')).length,16);assert.equal(inspected.frames[0].transparent,0);
await assert.rejects(call({dryRun:false,outputName:'changed-source'}),/review evidence/);
console.log('PASS opaque background warnings and changed-source approval invalidation');
